[management]
# 需要搜刮的资源目录
resource_folder = 'resrc/'
# 整理好的资源目录
managed_folder = 'scraped/'

[rule]
detect_suffixes = ['.webm', '.mkv', '.flv', '.avi', '.mts', '.m2ts', '.ts', '.3gp', '.mov',
    '.wmv', '.rmvb', '.mp4', '.m4p', '.m4v', '.mpg', '.mpeg', '.mpv', '.m2v', '.iso']

escape_folders = ['scraped/']
